In [2]:
S0= int(input("請輸入當前股價"))
time = float(input("請輸入到期時間(年化)"))
rf = float(input("請輸入無風險利率"))
sigma = float(input("請輸入波動度"))
dt = time / 100
N = int(input("請輸入模擬次數"))
SK = int(input("請輸入執行價格"))
c_or_p = input("請輸入選擇權類型(C or P)")
stock_price=S0 
import numpy as np

請輸入當前股價100
請輸入到期時間(年化)0.05
請輸入無風險利率0.01
請輸入波動度0.35
請輸入模擬次數100000
請輸入執行價格100
請輸入選擇權類型(C or P)C


In [3]:
arr_1 = np.random.randn(N,100)

In [4]:
import math

for i in range(N):
    for k in range(100):
        if k == 0:
            arr_1[i,k] = stock_price
            S0 = arr_1[i,k]
            
        else:
            ds = S0 * rf * dt + sigma * S0 * math.sqrt(dt) * arr_1[i,k]
            arr_1[i,k] = ds + S0
            S0 = arr_1[i,k]

In [5]:
arr_1

array([[100.        ,  99.64284649, 100.88713958, ..., 103.01177925,
        103.43148442, 103.28739445],
       [100.        ,  99.51435394,  99.75761722, ..., 102.11112792,
        102.59895014, 102.1625618 ],
       [100.        , 100.47339533,  99.74091485, ...,  93.64260528,
         93.07345471,  94.02893859],
       ...,
       [100.        , 101.08411405, 101.16723457, ..., 107.32322876,
        106.19398392, 106.42847779],
       [100.        ,  99.88566954, 101.09132237, ..., 102.32081388,
        102.61316425, 102.24463466],
       [100.        , 100.23673303,  98.99586501, ...,  97.49550584,
         99.19650688, 100.17230876]])

In [6]:
X = []
X_bar = []
for i in range(N):
    X.append (math.exp(-rf*time) * max(0,arr_1[i,-1]-SK)) 
    X_bar.append(math.exp(-rf*time)*(arr_1[i,-1]-SK))
X_matrix = np.array(list(zip(X,X_bar))) 

In [7]:
X_matrix

array([[ 3.28575116,  3.28575116],
       [ 2.16148079,  2.16148079],
       [ 0.        , -5.96807663],
       ...,
       [ 6.42526436,  6.42526436],
       [ 2.24351262,  2.24351262],
       [ 0.17222263,  0.17222263]])

In [8]:
cov=np.cov(X_matrix.T)

In [9]:
cov_x_xbar=cov[0,1]

In [10]:
var_xbar = stock_price ** 2 *(math.exp(sigma**2*time)-1) 

In [11]:
theta = cov_x_xbar/var_xbar

In [12]:
theta 

0.5234013023064287

In [13]:
Y_theta=[]
E_xbar = stock_price-(math.exp(-rf*time)*SK)
for i in range(N):
    Y_sample = X[i] + theta*(E_xbar-X_bar[i])
    Y_theta.append(Y_sample)

In [14]:
arr_Y_theta=np.array(Y_theta)
arr_Y_theta

array([1.59214825, 1.05632245, 3.1498626 , ..., 3.08843615, 1.09541872,
       0.1082446 ])

In [15]:
std=np.std(arr_Y_theta) 

In [16]:
mean = np.mean(arr_Y_theta)
print("option price")
print(mean)
CI_1 = mean +1.96 * std / math.sqrt(N)
CI_2 = mean - 1.96 * std / math.sqrt(N)
confidence_intervial = CI_2,CI_1
length3 = CI_1 - CI_2
print("confidence_interval:")
print(confidence_intervial)
print("confidence_width:")
print(length3)

option price
3.1183802958375324
confidence_interval:
(3.103848494364846, 3.1329120973102187)
confidence_width:
0.02906360294537258
