 Monte_carol simulation (Europen)

In [1]:
#歐式買賣權參數輸入
S0= int(input("請輸入當前股價"))
time = float(input("請輸入到期時間(年化)"))
rf = float(input("請輸入無風險利率"))
sigma = float(input("請輸入波動度"))
dt = time / 100
N = int(input("請輸入模擬次數"))
SK = int(input("請輸入執行價格"))
c_or_p = input("請輸入選擇權類型(C or P)")
stock_price=S0 
import numpy as np

請輸入當前股價100
請輸入到期時間(年化)0.05
請輸入無風險利率0.01
請輸入波動度0.35
請輸入模擬次數100000
請輸入執行價格100
請輸入選擇權類型(C or P)C


In [2]:
#產生一個常態分配的隨機樣本(對偶變量則差負號)
arr_1 = np.random.randn(N,100)
arr_2 = -(arr_1.copy())

In [3]:
arr_1

array([[ 1.0844438 , -1.15558374, -0.49088491, ..., -0.96827514,
         0.72073152,  2.01746982],
       [-1.5927491 , -0.16175024,  0.28145362, ..., -1.1331205 ,
        -1.85646443, -0.15591456],
       [-0.74757126,  1.35029931, -0.67863855, ..., -0.42568024,
         0.89112412,  1.17531603],
       ...,
       [ 1.38391487,  0.54922995,  0.48912433, ..., -0.51300975,
         0.90991471,  1.03128222],
       [-0.97658427,  0.34031258,  0.94698557, ...,  0.68381845,
         0.27942373, -0.61817253],
       [-1.32920514,  0.17144214, -0.72824002, ..., -0.2974576 ,
         0.22828817,  0.92618243]])

In [4]:
arr_2

array([[-1.0844438 ,  1.15558374,  0.49088491, ...,  0.96827514,
        -0.72073152, -2.01746982],
       [ 1.5927491 ,  0.16175024, -0.28145362, ...,  1.1331205 ,
         1.85646443,  0.15591456],
       [ 0.74757126, -1.35029931,  0.67863855, ...,  0.42568024,
        -0.89112412, -1.17531603],
       ...,
       [-1.38391487, -0.54922995, -0.48912433, ...,  0.51300975,
        -0.90991471, -1.03128222],
       [ 0.97658427, -0.34031258, -0.94698557, ..., -0.68381845,
        -0.27942373,  0.61817253],
       [ 1.32920514, -0.17144214,  0.72824002, ...,  0.2974576 ,
        -0.22828817, -0.92618243]])

In [5]:
S1 = S0
import math

for i in range(N):
    for k in range(100):
        if k == 0:
            arr_1[i,k] = stock_price
            arr_2[i,k] = stock_price
            S0 = arr_1[i,k]
            S1 = arr_2[i,k]
            
        else:
            ds = S0 * rf * dt + sigma * S0 * math.sqrt(dt) * arr_1[i,k]
            ds_1 = S1 * rf * dt + sigma * S1 * math.sqrt(dt) * arr_2[i,k]
            arr_1[i,k] = ds + S0
            arr_2[i,k] = ds_1 + S1
            S0 = arr_1[i,k]
            S1 = arr_2[i,k]

In [6]:
arr_1

array([[100.        ,  99.09611267,  98.71590248, ..., 108.80526447,
        109.41953725, 111.14773118],
       [100.        ,  99.87391042, 100.09440434, ...,  97.41328141,
         95.99843802,  95.88177837],
       [100.        , 101.05727636, 100.52104758, ..., 101.58242771,
        102.29138665, 103.23280526],
       ...,
       [100.        , 100.43034042, 100.81529025, ..., 100.78725748,
        101.50548854, 102.32525296],
       [100.        , 100.26683672, 101.01044911, ..., 122.82434013,
        123.09355102, 122.49864416],
       [100.        , 100.1346747 ,  99.56446984, ...,  93.85254401,
         94.02069375,  94.70267511]])

In [7]:
arr_2

array([[100.        , 100.90488733, 101.29304644, ...,  91.40407199,
         90.8889537 ,  89.45434438],
       [100.        , 100.12708958,  99.90703798, ..., 102.21280635,
        103.6983808 , 103.82543458],
       [100.        ,  98.94372364,  99.46972695, ...,  97.88414412,
         97.2019749 ,  96.3083677 ],
       ...,
       [100.        ,  99.57065958,  99.19000061, ...,  98.74629444,
         98.04359518,  97.25276965],
       [100.        ,  99.73416328,  98.99549872, ...,  80.97389275,
         80.79722095,  81.18851909],
       [100.        ,  99.8663253 , 100.43600074, ..., 106.05764078,
        105.86868451, 105.10182214]])

In [8]:
payoff_list_1 = []
payoff_list_2 = []
import statistics as sc
if c_or_p == "C" :
    arr_S = arr_1[:,-1] - SK
    arr_S2 = arr_2[:,-1] - SK
if c_or_p == "P" :
    arr_S = SK-arr_1[:,-1] 
    arr_S2 =SK-arr_2[:,-1]
    
for i in range(N):
    if arr_S[i] > 0 :
        payoff_list_1.append(arr_S[i]* math.exp(-rf * time))
    else :
        payoff_list_1.append(0)
for i in range(N):
    if arr_S2[i] > 0 :
        payoff_list_2.append(arr_S2[i]* math.exp(-rf * time))
    else :
        payoff_list_2.append(0)
        
call_price= round((sc.mean(payoff_list_1) +sc.mean(payoff_list_2))/2 ,3)
print("call price is : ")
print(call_price )

payoff_arr1 = np.array(payoff_list_1)
payoff_arr2 = np.array(payoff_list_2)
payoff_arr = np.concatenate((payoff_arr1,payoff_arr2))


call price is : 
3.137


In [9]:
N1 = len(payoff_arr1)
N2 = payoff_arr.shape[0]

計算信賴區間

In [10]:
import statistics as sc

In [11]:
#計算原本的信賴區間
std1=sc.stdev(payoff_arr1)
mean1=sc.mean(payoff_arr1)

CI_1 = mean1 +1.96 * std1 / math.sqrt(N1)
CI_2 = mean1 - 1.96 * std1 / math.sqrt(N1)
confidence_intervial = CI_2,CI_1
length = CI_1 - CI_2
print("confidence_interval(without accuracy):")
print(confidence_intervial)
print("length(without accuracy):")
print(length)

confidence_interval(without accuracy):
(3.101209713426617, 3.1604444505554623)
length(without accuracy):
0.05923473712884508


antithetic variate

In [12]:
std2=sc.stdev(payoff_arr)
mean=sc.mean(payoff_arr)
CI_1 = mean1 +1.96 * std2 / math.sqrt(N2)
CI_2 = mean1 - 1.96 * std2 / math.sqrt(N2)
confidence_intervial = CI_2,CI_1
length2 = CI_1 - CI_2
print("confidence_interval(with accuracy):")
print(confidence_intervial)
print("length(without accuracy):")
print(length2)

confidence_interval(with accuracy):
(3.109840277925965, 3.1518138860561145)
length(without accuracy):
0.04197360813014939


In [13]:
length2 / length

0.7085978627515479